DROP TABLE IF EXISTS users CASCADE;


-- 01 USER TABLE
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR,
  created_at TIMESTAMP, 
  role VARCHAR(255) NOT NULL DEFAULT 'user'
)