INSERT INTO
 questions (
  id,
  question,
  answer_a,
  answer_b,
  answer_c,
  answer_d,
  correct_answer,
  explanation,
  language
)
VALUES
(
  1,
  'Who developed Python Programming Language?',
  'Wick van Rossum',
  'Rasmus Lerdorf',
  'Guido van Rossum',
  'Niene Stom',
  'answer_c',
  'Python language is designed by a Dutch programmer Guido van Rossum in the Netherlands.',
  'Python'
),
(
  2,
  'Which type of Programming does Python support?',
  'object-oriented programming',
  'structured programming',
  'functional programming',
  'all of the mentioned',
  'answer_d',
  'Python is an interpreted programming language, which supports object-oriented, structured, and functional programming.',
  'Python'
),
(
  3,
  'Is Python case sensitive when dealing with identifiers?',
  'no',
  'yes',
  'machine dependent',
  'none of the mentioned',
  'answer_a',
  'Case is always significant.',
  'Python'
),
(
  4,
  'Which of the following is the correct extension of the Python file?',
  '.python',
  '.py',
  '.pl',
  '.p',
  'answer_b',
  '.py is the correct extension of the Python file. Python programs can be written in any text editor. To save these programs we need to save in files with file extension .py.',
  'Python'
),
(
  5,
  'All keywords in Python are in _________',
  'Capitalized',
  'lower case',
  'UPPER CASE',
  'None of the mentioned',
  'answer_d',
  'True, False and None are capitalized while the others are in lower case.',
  'Python'
),
(
  7,
  'Is Python code compiled or interpreted?',
  'Python code is both compiled and interpreted',
  'Python code is neither compiled nor interpreted',
  'Python code is only compiled',
  'Python code is only interpreted',
  'answer_b',
  'Many languages have been implemented using both compilers and interpreters, including C, Pascal, and Python.',
  'Python'
),
(
  8,
  'What is the order of namespaces in which Python looks for an identifier?',
  'Python first searches the built-in namespace, then the global namespace and finally the local namespace',
  'Python first searches the built-in namespace, then the local namespace and finally the global namespace',
  'Python first searches the local namespace, then the global namespace and finally the built-in namespace',
  'Python first searches the global namespace, then the local namespace and finally the built-in namespace',
  'answer_c',
  'Python first searches for the local, then the global and finally the built-in namespace.',
  'Python'
),
(
  9,
  'Which one of the following is not a keyword in Python language?',
  'pass',
  'eval',
  'assert',
  'nonlocal',
  'answer_b',
  'eval can be used as a variable.',
  'Python'
),
(
  10,
  'Which module in the python standard library parses options received from the command line?',
  'getarg',
  'getopt',
  'main',
  'os',
  'answer_b',
  'getopt parses options received from the command line.',
  'Python'
),
(
  11,
  'Which of the following statements is used to create an empty set in Python?',
  '()',
  '[]',
  '{}',
  'set()',
  'answer_d',
  '{ } creates a dictionary not a set. Only set() creates an empty set.',
  'Python'
),
(
  12,
  'To add a new element to a list we use which Python command?',
  'list1.addEnd(5)',
  'list1.addLast(5)',
  'list1.append(5)',
  'list1.add(5)',
  'answer_c',
  'We use the function append to add an element to the list.',
  'Python'
),
(
  13,
  'What are the two main types of functions in Python?',
  'System function',
  'Custom function',
  'Built-in function & User defined function',
  'User function',
  'answer_c',
  'Explanation: Built-in functions and user defined ones. The built-in functions are part of the Python language. Examples are: dir(), len() or abs(). The user defined functions are functions created with the def keyword.',
  'Python'
),
(
  14,
  'Which of the following is a feature of Python DocString?',
  'In Python all functions should have a docstring',
  'Docstrings can be accessed by the __doc__ attribute on objects',
  'It provides a convenient way of associating documentation with Python modules, functions, classes, and methods',
  'All of the mentioned',
  'answer_d',
  'Python has a nifty feature called documentation strings, usually referred to by its shorter name docstrings. DocStrings are an important tool that you should make use of since it helps to document the program better and makes it easier to understand.',
  'Python'
),
(
  15,
  'Which of the following is the use of id() function in python?',
  'Wick van Rossum',
  'Rasmus Lerdorf',
  'Guido van Rossum',
  'Niene Stom',
  'answer_c',
  'Python language is designed by a Dutch programmer Guido van Rossum in the Netherlands.',
  'Python'
),
(
  16,
  'Who developed Python Programming Language?',
  'James Gosling',
  'Dennis Ritchie',
  'Guido van Rossum',
  'Bjarne Stroustrup',
  'answer_a',
  'Java programming was developed by James Gosling at Sun Microsystems in 1995. James Gosling is well known as the father of Java.',
  'Java'
),
(
  17,
  'Which statement is true about Java?',
  'Java is a sequence-dependent programming language',
  'Java is a code dependent programming language',
  ' Java is a platform-dependent programming language',
  ' Java is a platform-independent programming language',
  'answer_d',
  'Java is called Platform Independent Language as it primarily works on the principle of compile once, run everywhere.',
  'Java'
),
(
  18,
  'Which component is used to compile, debug and execute the java programs?',
  'JRE',
  'JIT',
  'JDK',
  'JVM',
  'answer_c',
  'JDK is a core component of Java Environment and provides all the tools, executables and binaries required to compile, debug and execute a Java Program.',
  'Java'
),
(
  19,
  'Which one of the following is not a Java feature?',
  'Object-oriented',
  'Use of pointers',
  'Portable',
  'Dynamic and Extensible',
  'answer_b',
  'Pointers is not a Java feature. Java provides an efficient abstraction layer for developing without using a pointer in Java. Features of Java Programming are Portable, Architectural Neutral, Object-Oriented, Robust, Secure, Dynamic and Extensible, etc.',
  'Java'
),
(
  20,
  'Which of these cannot be used for a variable name in Java?',
  'identifier & keyword',
  'identifier',
  'keyword',
  'none of the mentioned',
  'answer_c',
  'Keywords are specially reserved words that can not be used for naming a user-defined variable, for example: class, int, for, etc.',
  'Java'
),
(
  21,
  'Which of the following is a superclass of every class in Java?',
  'ArrayList',
  'Abstract class',
  'Object class',
  'String',
  'answer_c',
  'Object class is superclass of every class in Java.',
  'Java'
),
(
  22,
  'Which of the below is not a Java Profiler?',
  'JProfiler',
  'Eclipse Profiler',
  'JVM',
  'JConsole',
  'answer_c',
  'Memory leak is like holding a strong reference to an object although it would never be needed anymore. Objects that are reachable but not live are considered memory leaks. Various tools help us to identify memory leaks.',
  'Java'
),
(
  23,
  'Which of these statements is incorrect about Thread?',
  'start() method is used to begin execution of the thread',
  'run() method is used to begin execution of a thread before start() method in special cases',
  'A thread can be formed by implementing Runnable interface only',
  'A thread can be formed by a class that extends Thread class',
  'answer_b',
  'run() method is used to define the code that constitutes the new thread, it contains the code to be executed. start() method is used to begin execution of the thread that is execution of run(). run() itself is never used for starting execution of the thread.',
  'Java'
),
(
  24,
  'Which of these keywords are used for the block to be examined for exceptions?',
  'check',
  'throw',
  'catch',
  'try',
  'answer_d',
  'try is used for the block that needs to checked for exception.',
  'Java'
),
(
  25,
  'Which one of the following is not an access modifier?',
  'Protected',
  'Void',
  'Public',
  'Private',
  'answer_b',
  'Public, private, protected and default are the access modifiers.',
  'Java'
),
(
  26,
  'What is the numerical range of a char data type in Java?',
  '0 to 256',
  '0 to 65535',
  '-128 to 127',
  '0 to 32767',
  'answer_b',
  'Char occupies 16-bit in memory, so it supports 216 i:e from 0 to 65535.',
  'Java'
),
(
  27,
  'Which of the following is true about servlets?',
  'Servlets can use the full functionality of the Java class libraries',
  'Servlets execute within the address space of web server, platform independent and uses the functionality of java class libraries',
  'Servlets execute within the address space of web server',
  'Servlets are platform-independent because they are written in java',
  'answer_b',
  'Servlets execute within the address space of a web server. Since it is written in java it is platform independent. The full functionality is available through libraries.',
  'Java'
),
(
  28,
  'Which class provides system independent server side implementation?',
  'Server',
  'ServerReader',
  'Socket',
  'ServerSocket',
  'answer_d',
  'ServerSocket is a java.net class which provides system independent implementation of server side socket connection.',
  'Java'
),
(
  29,
  'What is the extension of compiled java classes?',
  '.txt',
  '.js',
  '.class',
  '.java',
  'answer_c',
  'The compiled java files have .class extension.',
  'Java'
),
(
  30,
  'What is Truncation in Java?',
  'Floating-point value assigned to a Floating type',
  'Floating-point value assigned to an integer type',
  'Integer value assigned to floating type',
  'Integer value assigned to floating type',
  'answer_b',
  NULL,
  'Java'
),
(
  31,
  'Who invented C++?',
  'Dennis Ritchie',
  'Ken Thompson',
  'Brian Kernighan',
  'Bjarne Stroustrup',
  'answer_d',
  'Bjarne Stroustrup is the original creator of C++ in 1979 at AT&T Bell Labs.',
  'C++'
),
(
  32,
  'What is C++?',
  'C++ is an object oriented programming language',
  'C++ is a procedural programming language',
  'C++ supports both procedural and object oriented programming language',
  'C++ is a functional programming language',
  'answer_c',
  'C++ supports both procedural(step by step instruction) and object oriented programming (using the concept of classes and objects).',
  'C++'
),
(
  33,
  'Which of the following is the correct syntax of including a user defined header files in C++?',
  '#include [userdefined]',
  '#include “userdefined”',
  '#include <userdefined.h>',
  '#include <userdefined>',
  'answer_b',
  'C++ uses double quotes to include a user-defined header file. The correct syntax of including user-defined is #include “userdefinedname”.',
  'C++'
),
(
  34,
  'Which of the following is used for comments in C++?',
  '/* comment */',
  '// comment */',
  '// comment',
  'both // comment or /* comment */',
  'answer_d',
  'Both the ways are used for commenting in C++ programming. // is used for single line comments and /* … */ is used for multiple line comments.',
  'C++'
),
(
  35,
  'Which of the following user-defined header file extension used in c++?',
  'hg',
  'cpp',
  'h',
  'hf',
  'answer_c',
  '.h extensions are used for user defined header files. To include a user defined header file one should use #include”name.h” i.e. enclosed within double quotes.',
  'C++'
),
(
  36,
  'Which of the following is a correct identifier in C++?',
  'VAR_1234',
  '$var_name',
  '7VARNAME',
  '7var_name',
  'answer_a',
  'The rules for writing an identifier is as follows:
  i) may contain lowercase/uppercase letters, digits or underscore(_) only
  ii) should start with a non-digit character
  iii) should not contain any special characters like @, $, etc.',
  'C++'
),
(
  37,
  'Which of the following approach is used by C++?',
  'Left-right',
  'Right-left',
  'Bottom-up',
  'Top-down',
  'answer_c',
  'C++ is an object-oriented language and OOL uses a bottom-up approach to solve/view a problem.',
  'C++'
),
(
  38,
  'What is virtual inheritance in C++?',
  'C++ technique to enhance multiple inheritance',
  'C++ technique to ensure that a private member of the base class can be accessed somehow',
  'C++ technique to avoid multiple inheritances of classes',
  'C++ technique to avoid multiple copies of the base class into children/derived class',
  'answer_d',
  'Virtual inheritance is a C++ technique with which it ensures that a derived class contains only one copy of the base classs variables. Refer Wikipedia for more info.',
  'C++'
),
(
  39,
  'What is the difference between delete and delete[] in C++?',
  'delete is syntactically correct but delete[] is wrong and hence will give an error if used in any case',
  'delete is used to delete normal objects whereas delete[] is used to pointer objects',
  'delete is a keyword whereas delete[] is an identifier',
  'delete is used to delete single object whereas delete[] is used to multiple(array/pointer of) objects',
  'answer_d',
  'delete is used to delete a single object initiated using new keyword whereas delete[] is used to delete a group of objects initiated with the new operator.
',
  'C++'
),
(
  40,
  'Which of the following type is provided by C++ but not C?',
  'double',
  'float',
  'int',
  'bool',
  'answer_d',
  'C++ provides the boolean type to handle true and false values whereas no such type is provided in C.',
  'C++'
),
(
  41,
  'By default, all the files in C++ are opened in _________ mode.',
  'Binary',
  'VTC',
  'Text',
  'ISCII',
  'answer_c',
  'By default, all the files in C++ are opened in text mode. They read the file as normal text.',
  'C++'
),
(
  42,
  'What is abstract class in C++?',
  'Any Class in C++ is an abstract class',
  'Class from which any class is derived',
  'Class specifically used as a base class with atleast one virtual functions',
  'Class specifically used as a base class with atleast one pure virtual functions',
  'answer_d',
  'An abstract class is defined as a class which is specifically used as a base class. An abstract class should have atleast one pure virtual function.',
  'C++'
),
(
  43,
  'Which of the following constructors are provided by the C++ compiler if not defined in a class?',
  'Copy constructor',
  'Default constructor',
  'Assignment constructor',
  'All of the mentioned',
  'answer_d',
  'If a programmer does not define the above constructors in a class the C++ compiler by default provides these constructors to avoid error on basic operations.',
  'C++'
),
(
  44,
  'Which concept allows you to reuse the written code in C++?',
  'Inheritance',
  'Polymorphism',
  'Abstraction',
  'Encapsulation',
  'answer_a',
  'Inheritance allows you to reuse your already written code by inheriting the properties of written code into other parts of the code, hence allowing you to reuse the already written code.',
  'C++'
),
(
  45,
  'How structures and classes in C++ differ?',
  'Structures by default hide every member whereas classes do not',
  'In Structures, members are public by default whereas, in Classes, they are private by default',
  'Structures cannot have private members whereas classes can have',
  'In Structures, members are private by default whereas, in Classes, they are public by default',
  'answer_b',
  'Structure members are public by default whereas, class members are private by default. Both of them can have private and public members.',
  'C++'
),
(
  46,
  'Ruby is ?',
  'procedural language',
  'scripting language',
  'Markup language',
  'Stylesheet language',
  'answer_b',
  'Ruby is a scripting language',
  'Ruby'
),
(
  47,
  'Which of the following is supported by Ruby?',
  'Multiple Programming Paradigms',
  'Dynamic Type System',
  'Automatic Memory Management',
  'All of the Mentioned',
  'answer_d',
  'Ruby supports all the features because it is a object oriented programming language.',
  'Ruby'
),
(
  48,
  'Which of the following are valid floating point literal?',
  '5',
  '2',
  '0.5',
  'none of the mentioned',
  'answer_c',
  'floating point literals are valid only when they have digits on both the sides of decimal point.',
  'Ruby'
),
(
  49,
  'What is the output of: Ruby.length #to find the length of given string',
  '4 to find the length of given string',
  '4',
  'To find the length of given string',
  'Ruby',
  'answer_b',
  'It finds the length of string.',
  'Ruby'
),
(
  50,
  'Why do we use =begin and =end?',
  'To mark the start and end of multiline comment',
  'To comment multiple lines',
  'To avoid the use of # again and again',
  'All of the mentioned',
  'answer_d',
  'Easier way to comment multiple lines.',
  'Ruby'
),
(
  51,
  'What is the output of: boolean_1 = 77 less than 78 puts(boolean_1) ',
  'Nil',
  'True',
  'False',
  'Error',
  'answer_b',
  'As 77 is less than 78 hence the boolean value will be printed as true. Output: True',
  'Ruby'
),
(
  52,
  'What is the role of ! at the end of the capitalize method?',
  'It is the syntax for using capitalize method',
  'It modifies the value stored in the variable',
  'It indicates the termination of string',
  'None of the mentioned',
  'answer_b',
  'It is used for modifying the variable.',
  'Ruby'
),
(
  53,
  'Which sequence can be used to substitute the value of any ruby expression in a string?',
  '#(expr)',
  '#{expr}',
  '#expr',
  'None of the mentioned',
  'answer_b',
  '#{expr} is valid.',
  'Ruby'
),
(
  54,
  'What will be the output of: Eric.irreverse?',
  'Eric',
  'cirE',
  'undefined method',
  'None of the mentioned',
  'answer_c',
  'There is no predefined method named irreverse in ruby. Output: undefined method irreverse for eric:String',
  'Ruby'
);